// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7exL2Zwjy",
    "aws_user_pools_web_client_id": "3ft0k4kig93h73ca895e35mq2e",
    "oauth": {
        "domain": "https://demomon-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://web.hwmplatform.com/",
        "redirectSignOut": "https://web.hwmplatform.com/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default config;
