// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:447e1ceb-4952-44ce-92ec-21e848b6a210",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hG3tQKW3s",
    "aws_user_pools_web_client_id": "6bt21spu17al063p1rf19njr7e",
    "oauth": {
        "domain": "ad.hwmplatform.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://web.hwmplatform.com/",
        "redirectSignOut": "https://web.hwmplatform.com/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default config;
